name: Deploy Webpage

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy webpage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        run: |
          rustup toolchain update stable
          rustup toolchain install stable -t wasm32-unknown-unknown
          cargo install trunk wasm-bindgen-cli
      - name: Set up C#
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Compile
        run: |
          trunk build
      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist
      - name: Switch to gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Remove old files
        run: rm ./*
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Push to gh-pages
        run: |
          ls -la
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git status
          git fetch origin
          git commit -m "Deploy website at commit $(git rev-parse origin/master)"
          git push
